name: Deployment-of-python-app
on: [push]
jobs: 
   build-and-depoly:
      runs-on: ubuntu-latest
      steps:
          - run: echo "this has been triggred " 
          - name: checkout repo content
            uses: actions/checkout@v2
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.9
          - uses: actions/cache@v2
            with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                                 ${{ runner.os }}-pip-
          - name: install pip
            run: |
              sudo apt-get install python3-pip
              if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          - name: install pylint and pycodestyle
            run: |
              pip install pylint
              pip install pycodestyle
          - name: Run pylint
            run: |
              python3 lint_test.py
          - name: Run pycodestyle
            run: |
               pycodestyle *.py    
