name: QA-Selenium-Staging-Sanity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        sudo apt-get install libkrb5-dev
        sudo apt-get install python3-pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Running static analysis - MACCABE
      run: python3 ./scripts/maccabe.py
    - name: Running static analysis - Python lint
      run: sh ./scripts/python_lint.sh        
    - name: Running static analysis - Xenon
      run: sh ./scripts/xenon.sh        
    - name: Running unit tests
      run: sh ./scripts/run_unit_tests.sh